package tw.com.firstbank.fcbcore.ffx.service.commontool.domain.ffxtsserialnumber.vo;

import java.io.Serial;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * The type of FX_SERIAL_NUMBER's business primary key. 外匯序號檔 的商業邏輯複合鍵 Generated by st1 tool
 */
@ToString
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class Identifier implements Serializable {

	@Serial
	private static final long serialVersionUID = 3675421525115922199L;

	@Column(name = "SYSTEM_TYPE")
	private String systemType;

	@Column(name = "SERIAL_ID")
	private String serialId;

}
