## application.yml (用於切換不同部署環境使用)
## application-local.yml (用於XP, FCB開發）
## application-dev.yml（用於佈署到DEV環境使用，目前 DEV TAP使用）
## application-sit.yml（用於佈署到SIT環境使用）
## application-uat.yml（用於佈署到UAT環境使用）
## application-prod.yml（用於佈署到PROD環境使用）
## application-systexlocal.yml（用於精誠開發）
## application-systexdev.yml（用於佈署到精誠環境使用，目前精誠TAP使用）

## 第三方套件的參數
############################
server:
  port: 8080
  shutdown: graceful
  error:
    whitelabel:
      enabled: false

  compression:
    enabled: true
    min-response-size: 256
    mime-types: text/html,text/xml,text/plain,application/json,application/xml,text/css,application/javascript,image/svg+xml

spring:
  transaction:
    timeout: 36000
  application:
    name: ffx-service-commontool
  lifecycle:
    timeout-per-shutdown-phase: 60s

  ## enabling overriding by setting spring.main.allow-bean-definition-overriding=true
  main:
    allow-bean-definition-overriding: true

  datasource:
    ## 此服務 aggregate 連線設定
    main:
      jdbcUrl: jdbc:oracle:thin:@10.20.152.41:1523/CORREMIT
      username: firse
      password: firse123
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # for lazy load no session exception
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 2
    hibernate:
      generate-ddl: false
      ## none, validate, update, create, create-drop
      ddl-auto: none
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
      fail-on-empty-beans: false
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static
  resources:
    add-mappings: false

logging:
  config: classpath:logback-default.xml
############################

## Framework定義的參數
############################
fcb-framework:
  ## 服務基本設定資訊
  ## length.system-type（系統別長度）
  ## length.service-name（服務名稱長度）
  ## length.error-type（錯誤訊息分類長度）
  ## length.error-code（錯誤訊息編碼長度）
  ## information.system-type（系統別）
  ## information.service-name（服務名稱）
  service:
    length:
      system-type: 3
      service-name: 2
      error-type: 1
      error-code: 4
    information:
      system-type: FFX
      service-name: TS
############################

## 服務自定義的參數
############################
ffx-service-commontool:

serial-number:
  optimistic-lock-retry-limit: 10
############################